%YAML 1.2
# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
---
config:
  default: true

  # Allow arbitrary line length
  #
  # Reason: We apply the one-sentence-per-line rule. A sentence may get longer than 80 characters, especially if links are contained.
  #
  # Detail: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
  MD013: false

  # Allow repeated heading at the same level, within different nesting hierarchies.
  #
  # Reason: We have repeated sections of information in some limited cases.
  #
  # Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content
  MD024:
    allow_different_nesting: true

  # Allow inline HTML
  #
  # Reason: The <br/> and <code> tags in particular are useful for making blocks of text more readbale in a table cell.
  #
  # Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033---inline-html
  MD033:
    allowed_elements: ["br", "code"]

fix: true

noInlineConfig: true

ignores:
  # Reason: auto-generated by a tool that does not confirm to these lint rules
  - CHANGELOG.md

outputFormatters:
  - - markdownlint-cli2-formatter-default
  - - markdownlint-cli2-formatter-codequality
